services:
  open-webui:
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main

volumes:
  open-webui:
