services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
