services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - '8443:8443'
      - '8443:8443/udp'
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}

volumes:
  caddy_data:
  caddy_config:
