services:
  postgres:
    image: postgres:18.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=123456
