services:
  open-webui:
    ports:
      - 3000:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:cuda

volumes:
  open-webui:
